spring.application.name=BankLedger

# Base de datos en memoria
spring.datasource.url=jdbc:h2:mem:ledgerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate creará las tablas automáticamente basadas en LedgerEntity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
